---
    - name: Update apt cache
      become: true  # Run the task with root privileges
      apt:
        update_cache: yes
  
    - name: Install Python 3.8
      become: true
      apt:
        name:
          - python3.8
          - python3.8-dev
          - python3.8-venv
        state: present
